baseURL = 'https://tailedfaerie.com/'
languageCode = 'en-us'
title = 'TailedFaerie Studio'
comingsoon="Coming soon..."
theme = "gohugo-theme-tailedfaerie"
[params]
  subtitle = 'Welcome o/'

[params.contact]
  email = 'contact@tailedfaerie.com'
  
[params.author]
  name = "Kevin Schnurbusch"
  location = "Germany"
